### ISSUE TITLE
Solid Black Background

### ISSUE THREAD

**Issue by Francewhoa** [z-------------/New-New-Tab-Page#10]
Thanks for this extension :) I posted a positive review at https://chrome.google.com/webstore/detail/new-new-tab-page/nndegnhfodohkemfnmalamgebofbgjcc/reviews

This is a suggestion. Under "Options" menu > "Background" section > "Preset backgrounds" field. How about adding a "Solid black" option?

On some computers and devices it would be useful to set new tab to a solid black background. So that to extend battery life, and healthier for the eyes in low light environment or night.

I would be happy to contribute testing

**Comment by Francewhoa** [comment]
@Francewhoa :) Note to myself. This screenshot show the location of the "Preset backgrounds" field
![suggestion-solid-black-2017-10-07](https://user-images.githubusercontent.com/119942/31311616-e2668bdc-ab64-11e7-9512-9bd3ef200c96.jpg)

**Comment by z-------------** [comment]
Thanks for your suggestion and kind words. I have added this option in commit 57e2b3ec6d1a6e5589fc33275ffaf026efb0f7fa. Testing probably won't be needed since it's a very trivial change but please feel free to do so :smile:
I will publish the update along with a few other small changes soon on the Web Store.

**Comment by Francewhoa** [comment]
Thanks Zachary :)
