### ISSUE TITLE
Doesn't seem to find an icon for /.

### ISSUE THREAD

**Issue by shellscape** [z-------------/New-New-Tab-Page#6]
Great extension, really loving the experience so far. Unfortunately, it's not finding an icon for slashdot, which was surprising.

_Edit_ Add http://getvideostream.com/ to the list.

**Comment by z-------------** [comment]
Thanks for reporting this. The problem was that NNTP was only looking for icons referred to in `link` elements in the `head` of the document. Slashdot had theirs in the `body`, and GetVideoStream didn't have one at all and relied on `favicon.ico`. I made NNTP handle both of these cases correctly with commit bb6148f.
😄

**Comment by z-------------** [comment]
By the way, thank you for the kind words. I'm glad that people are enjoying my work 😄
